### ISSUE TITLE
Expose `transaction` field in `TransactionDetails`

### ISSUE THREAD

**Issue by darkvoid32** [bitcoindevkit/bdk-ffi#172] opened 2022-07-25 13:55 UTC
Without the `transaction` field we are unable to calculate the transaction size since we do not have the input and output transactions. Exposing the field would allow us to calculate the transaction size to perform other operations like calculating fee rates which is important for bumping fees on transactions.

**Comment by thunderbiscuit** [comment] 2022-07-25 17:52
Related to bitcoindevkit/bdk#524.

**Comment by thunderbiscuit** [comment] 2022-11-02 15:03
This is really a duplicate of #84. Closing now.

**Closed by thunderbiscuit** 2022-11-02 15:03 UTC
